# Generated by Django 2.2.4 on 2019-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190817_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank-profile-picture-973460_640.png', upload_to=''),
        ),
    ]
