# Generated by Django 2.2.4 on 2019-08-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190819_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=32, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='blank-profile-picture-973460_640.png', upload_to='')),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userProfile')),
            ],
        ),
    ]
