# Generated by Django 2.1.1 on 2019-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parking_daily_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='parking_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=15)),
                ('reg_num', models.CharField(max_length=10)),
                ('slot_no', models.CharField(max_length=3)),
                ('start_tm', models.TimeField(auto_now_add=True)),
                ('current_tm', models.TimeField(auto_now=True)),
                ('occupied', models.BooleanField(default=True)),
                ('limit', models.PositiveIntegerField(choices=[(1, '30 min'), (2, '1 hr'), (3, '2 hrs')], default=1)),
            ],
        ),
    ]
