# Generated by Django 2.1.1 on 2019-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0002_remove_parking_slot_current_tm'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_slot',
            name='time_now',
            field=models.TimeField(auto_now=True),
        ),
    ]
