# Generated by Django 2.1.1 on 2019-07-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0003_parking_slot_time_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_slot',
            old_name='time_now',
            new_name='update_tm',
        ),
    ]
