# Generated by Django 2.1.1 on 2019-07-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0010_auto_20190724_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_daily_history',
            name='end_tm',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parking_daily_history',
            name='start_tm',
            field=models.DateTimeField(),
        ),
    ]
