# Generated by Django 2.1.1 on 2019-07-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0011_auto_20190724_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_daily_history',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
