# Generated by Django 2.1.1 on 2019-08-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0012_parking_daily_history_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_slot',
            name='slot_no',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
