# Generated by Django 2.1.1 on 2019-08-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0014_auto_20190802_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_slot',
            name='lh',
        ),
        migrations.RemoveField(
            model_name='parking_slot',
            name='lm',
        ),
        migrations.AddField(
            model_name='parking_slot',
            name='car_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Green', 'Green'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Beige', 'Beige')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parking_slot',
            name='car_maker',
            field=models.CharField(choices=[(1, 'Acura'), (2, 'Audi'), (3, 'BMW'), (4, 'Buick'), (5, 'Cadillac'), (6, 'Chevrolet'), (7, 'Chrysler'), (8, 'Dodge'), (9, 'Ford'), (10, 'GMC'), (11, 'Honda'), (12, 'Hyundai'), (13, 'Infiniti'), (14, 'Jaguar'), (15, 'Jeep'), (16, 'Kia'), (17, 'Land Rover'), (18, 'Lexus'), (19, 'Mazda'), (20, 'Mercedes Benz'), (21, 'Mini'), (22, 'Mitsubishi'), (23, 'Nissan'), (24, 'Ram'), (25, 'Subaru'), (26, 'Tesla'), (27, 'Toyota'), (28, 'Volkswagen'), (29, 'Volvo')], max_length=20, null=True),
        ),
    ]
