# Generated by Django 2.1.1 on 2019-08-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0015_auto_20190825_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_slot',
            name='limit',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
