# Generated by Django 2.1.1 on 2019-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_data', '0016_parking_slot_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_slot',
            name='limit',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
    ]
